### ISSUE TITLE
Exporter doesn't work with Blender 2.73

### ISSUE THREAD

**Issue by dKatara** [bdancer/vb25#139]
I installed the exporter correctly by unpacking it into scripts/startup but when I go into Blender user preferences and turn on the checkbox of V-Ray Exporter in the addons list, I get this popup:
![2015-03-05_12-47-40](https://cloud.githubusercontent.com/assets/8914735/6504337/4da15cc0-c336-11e4-84dd-ddbc4234f92b.png)

**Comment by bdancer** [comment]
Yes, it doesn't because it is no longer supported. Use vb30: https://github.com/bdancer/vb30/wiki
